apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: grpc
    protocol: TCP
    port: 6565
    targetPort: 6565
